FROM rust:1.73.0-alpine3.18
# musl-dev required for libc
# eudev-dev required for libudev
# linux-headers required for linux/hidraw.h for hidapi
RUN apk add --no-cache \
    musl-dev \
    eudev-dev \
    linux-headers
