[package]
name = "spl-calculator"
version = "1.0.1"
edition = "2021"

[features]
no-entrypoint = []
testing = [] # not used, added so that we can run cargo-test-sbf at workspace root to test all programs

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
generic_pool_calculator_interface = { workspace = true }
generic-pool-calculator-lib = { workspace = true }
generic-pool-calculator-onchain = { workspace = true }
sanctum-misc-utils = { workspace = true }
sol-value-calculator-onchain = { workspace = true }
solana-program = { workspace = true }
spl_calculator_interface = { workspace = true }
spl-calculator-lib = { workspace = true }

[dev-dependencies]
generic-pool-calculator-test-utils = { workspace = true }
sanctum-solana-test-utils = { workspace = true, features = ["token"] }
sanctum-token-ratio = { workspace = true }
solana-program-test = { workspace = true }
solana-readonly-account = { workspace = true, features = ["solana-sdk"]}
solana-sdk = { workspace = true }
test-utils = { workspace = true }
tokio = { workspace = true }
